### ISSUE TITLE
ERROR: dependency ‘highlite’ is not available for package ‘lookup’

### ISSUE THREAD

**Issue by sillasgonzaga** [jimhester/lookup#18]
What is that dependency and how do I get it?

**Comment by jimhester** [comment]
Install this package with devtools and it will be retrieved automatically.

```r
# install.packages("devtools")
devtools::install_github("jimhester/lookup")
```

**Comment by CGMossa** [comment]
I'm trying to install this package, and this (see below) does not work. 
`# install.packages("devtools")
devtools::install_github("jimhester/lookup")`
