### ISSUE TITLE
rlang triple bang operator (unquote and splice) prints as triple negation

### ISSUE THREAD

**Issue by eaurele** [jimhester/lookup#19]
Thanks for a really useful package.

Looking for instance at `lookup::lookup(dplyr:::rename.data.frame)` (in dplyr 0.7.4 with new rlang NSE):

```
function (.data, ...) 
{
  vars <- rename_vars(names(.data), !(!(!quos(...))))
  select_impl(.data, vars)
}
```  

Instead of [https://github.com/tidyverse/dplyr/blob/41e9eb858978ca1d139047913321ac0e2a69ba5b/R/dataframe.R#L122](https://github.com/tidyverse/dplyr/blob/41e9eb858978ca1d139047913321ac0e2a69ba5b/R/dataframe.R#L122) : 

```
rename.data.frame <- function(.data, ...) {
  vars <- rename_vars(names(.data), !!! quos(...))
  select_impl(.data, vars)
}
```

Triple bang operator (`!!!` or `UQS()`, "unquote and splice", [http://rlang.tidyverse.org/reference/quasiquotation.html](http://rlang.tidyverse.org/reference/quasiquotation.html)) is mistaken for a triple nested negation (`!(!(!()))`).

Probably same with double bang unquote operator (`!!`) but didn't check though.

**Comment by jimhester** [comment]
The way R code is displayed by lookup is handled solely by R's internal layout code.

It is recommended you install packages with source references by setting `options("keep.source" = TRUE, "keep.source.pkgs = TRUE)` to ensure source references are available.  If they are you will find the output is exactly that in the original source file, e.g.

```
> lookup::lookup(dplyr:::rename.data.frame)
dplyr:::rename.data.frame [S3 method, closure] dataframe.R#L122-125
function(.data, ...) {
  vars <- rename_vars(names(.data), !!! quos(...))
  select_impl(.data, vars)
}
<environment: namespace:dplyr>

// c++ source: src/select.cpp#L79-L86
DataFrame select_impl(DataFrame df, CharacterVector vars) {
  check_valid_colnames(df);
  if (is<GroupedDataFrame>(df)) {
    return select_grouped(GroupedDataFrame(df), SymbolVector(vars), SymbolVector(vars.names()));
  } else {
    return select_not_grouped(df, SymbolVector(vars), SymbolVector(vars.names()));
  }
}
```
