### ISSUE TITLE
Font issue on ubuntu gnome-terminal

### ISSUE THREAD

**Issue by FvD** [jimhester/lookup#3]
This looks great! Thanks.
I do have a font issue in my ubuntu gnome-terminal, making the output look like this:

![lookup_font](https://cloud.githubusercontent.com/assets/2441145/20852106/9c9bbcfc-b8a9-11e6-8da4-427f66f1ae86.png)

Is there a font dependency? Maybe something osx-ish that you've built on?

**Comment by jimhester** [comment]
No Mac OS specific things, it doesn't look like your terminal is interpreting the ANSI escape codes properly

**Comment by jimhester** [comment]
Do you get similar results from `cat(crayon::blue("test"))`?

**Comment by jimhester** [comment]
I tested this with a Ubuntu VM and it works as expected. From your screenshot I am guessing you are using [colorout](https://github.com/jalvesaq/colorout) and it's coloring is messing up the escaping done by the crayon package. Try running with `R --vanilla` and see if it works.

**Comment by FvD** [comment]
Yes, that is exactly it: I use `colorout` in my .Rprofile (for use with nvim-r). Running R --vanilla solves the issue. 

Do you feel this is an issue to be placed with @jalvesaq for colorout, or with @gaborcsardi for crayon?

**Comment by jimhester** [comment]
I think this is a colorout issue (https://github.com/jalvesaq/colorout/issues), it may be tricky to handle though...
